name: Task6
on:
  push:

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      commit-sha: ${{ steps.commit-step.sha }}
      branch-name: ${{ steps.branch-name.branch }}
      commit-message: ${{ steps.commit-message.message }}
    steps:
      - uses: actions/checkout@v5
      - name: Get Commit SHA
        id: commit-step
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "sha=$SHA >> $GITHUB_OUTPUT"
      - name: Get branch name
        id: branch-name
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "branch=$BRANCH_NAME >> $OUTPUT"
      - name: Commit message
        id: commit-message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "message=$COMMIT_MESSAGE >> $GITHUB_OUTPUT"
       

  build:
    runs-on: ubuntu-latest
    needs: info
    steps:
      - name: Check out the code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Print message
        run: echo "Building commit ${{ needs.info.commit_sha }} on ${{ needs.info.branch_name }}
  summary
    needs: 
      - info
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Print summary
        run: |
          echo "Summary: Built commit  ${{ needs.info.commit_sha }}" on ${{ needs.info.branch_name }}"
          echo "Commit message: ${{ needs.info.commit_message }}"
