name: Task6
on:
  push:

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.commit_step.commit_sha }}
      branch_name: ${{ steps.branch_name.branch_name }}
      commit_message: ${{ steps.commit_message.commit_message }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v5
      - name: Get Commit SHA
        id: commit_step
	run: |
          SHA=$(git rev-parse --short HEAD)
          echo "commit_sha=$SHA >> $GITHUB_OUTPUT"
      - name: Get branch name
        id: branch_name
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "branch_name=$BRANCH_NAME >> $OUTPUT"
      - name: Commit message
        id: commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "commit_message=$COMMIT_MESSAGE >> $GITHUB_OUTPUT"
       

  build:
    runs-on: ubuntu-latest
    needs: info
    steps:
      - name: Check out the code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Print message
        run: echo "Building commit ${{ needs.info.commit_sha }} on ${{ needs.info.branch_name }}
  summary
    needs: 
      - info
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Print summary
        run: |
          echo "Summary: Built commit  ${{ needs.info.commit_sha }}" on ${{ needs.info.branch_name }}"
          echo "Commit message: ${{ needs.info.commit_message }}"
